# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets

import sys
from PyQt5.QtWidgets import *



####这个是我自己随便写的一个弹窗，想把他加到主界面的左上角位置

class Ui_dialog_3(QWidget):
    def setupUi(self, dialog_2):
        dialog_2.setObjectName("dialog_2")
        dialog_2.resize(260, 240)
        self.pushButton_3 = QtWidgets.QPushButton(dialog_2)
        self.pushButton_3.setGeometry(QtCore.QRect(180, 150, 71, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.widget = QtWidgets.QWidget(dialog_2)
        self.widget.setGeometry(QtCore.QRect(40, 20, 210, 121))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)

        self.retranslateUi(dialog_2)
        QtCore.QMetaObject.connectSlotsByName(dialog_2)

    def retranslateUi(self, dialog_2):
        _translate = QtCore.QCoreApplication.translate
        dialog_2.setWindowTitle(_translate("dialog_2", "diaglog"))
        self.pushButton_3.setText(_translate("dialog_2", "应用"))
        self.pushButton.setText(_translate("dialog_2", "model1（应用于SIC）"))
        self.pushButton_2.setText(_translate("dialog_2", "model2（应用于其他）"))


if __name__ == '__main__':
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_dialog_3()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

    def show_diag(self):


        diag = QDialog()
        diag.setGeometry(0, 0, 260, 240)
        ui = Ui_dialog_3()
        ui.setupUi(diag)
        diag.exec()